[package]
name = "swiftide-docker-executor"
version = "0.2.3"
description = "A docker executor for swiftide agent tools"
license = "MIT"
readme = "README.md"
keywords = ["llm", "rag", "ai", "data", "openai"]
homepage = "https://swiftide.rs"
repository = "https://github.com/bosun-ai/swiftide-docker-executor"

edition = "2021"

[dependencies]
swiftide-core = "0.16"
swiftide-agents = "0.16"


bollard = { version = "0.18", features = ["buildkit"] }
thiserror = "2.0"
async-trait = "0.1"
ignore = "0.4"
tokio = { version = "1", default-features = false }
tokio-tar = "0.3"
uuid = { version = "1.11", features = ["v4"] }
tracing = "0.1"
indoc = "2.0"
anyhow = "1.0"
dirs = "5.0"

[dev-dependencies]
test-log = "0.2"
tempfile = "3.15"
